#!/bin/bash
apt-get update -y
apt-get install -y docker.io

systemctl start docker
systemctl enable docker

docker network create helpers-network
docker volume create helpers_data 


cat <<EOF > /etc/systemd/system/n8n.service
[Unit]
Description=n8n Helpers Workflow Automation Tool
After=docker.service
Requires=docker.service

[Service]
Restart=always
ExecStart=/usr/bin/docker run --rm -p 5678:5678 \
    --name helpers \
    -v helpers_data:/home/node/.n8n \
    -e WEBHOOK_URL=${webhook_url} \
    -e N8N_BASIC_AUTH_ACTIVE=true \
    -e N8N_BASIC_AUTH_USER=admin \
    -e N8N_BASIC_AUTH_PASSWORD=${helpers_root_password} \
    -e N8N_HOST=${n8n_host} \
    -e N8N_PORT=5678 \
    -e N8N_PROTOCOL=http \
    n8nio/n8n
ExecStop=/usr/bin/docker stop helpers

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd to apply the new service
systemctl daemon-reload
systemctl enable n8n
systemctl start n8n